language: c
cache: ccache
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - cmake
      - p7zip-full
      - gcc-multilib
      - g++-multilib
      - libx11-dev:i386
      - libxext-dev:i386
      - libgl1-mesa-dev
      - libasound-dev
      - zlib1g:i386
      - libstdc++6:i386
git:
  depth: 50
  submodules: true
jdk:
    - oraclejdk8
os:
    - linux

before_script:
    - sh scripts/travis_${TRAVIS_OS_NAME}_deps.sh
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ANDROID_HOME=$PWD/android-sdk-linux; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=${PATH}:$PWD/apache-ant-1.10.6/bin:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PWD/android-ndk; fi
script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_android_engine.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_mingw_engine.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/build_portable_linux_engine.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/travis_coverity_scan.sh; fi
after_script:
    - cd ${TRAVIS_BUILD_DIR}
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ccache --show-stats > ccache_stats.log; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh scripts/travis_upload.sh xash3d-mingw.7z xash3d-linux.7z xash3d-generic.apk; fi
before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
